version = 5.6.0
archive_dir = /etc/letsencrypt/archive/winshubagro.cloud
cert = /etc/letsencrypt/live/winshubagro.cloud/cert.pem
privkey = /etc/letsencrypt/live/winshubagro.cloud/privkey.pem
chain = /etc/letsencrypt/live/winshubagro.cloud/chain.pem
fullchain = /etc/letsencrypt/live/winshubagro.cloud/fullchain.pem
[renewalparams]
account = 5a138c11156244ae49faa70b65fcc2f2
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
winshubagro.cloud = /var/www/certbot
www.winshubagro.cloud = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-06-04T19:07:29
